// Generated by packages/scripts/build-do-migrations.ts. Do not edit by hand.
import journal from "./meta/_journal.json";

const m0000 = "CREATE TABLE `chat_messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`ts` integer NOT NULL,\n\t`user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`text` text NOT NULL\n);\n";

const migrationConfig = {
	journal,
	migrations: {
		m0000,
	},
};

export default migrationConfig;
