import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type Journal = {
	entries?: {
		idx: number;
		tag: string;
	}[];
};

const migrationsDir = process.argv[2] ?? "drizzle";
const journalPath = path.join(migrationsDir, "meta", "_journal.json");
const outputPath = path.join(migrationsDir, "migrations.ts");

const journal = JSON.parse(await readFile(journalPath, "utf8")) as Journal;
const entries = [...(journal.entries ?? [])].sort((a, b) => a.idx - b.idx);

const migrationConstants: string[] = [];
const migrationEntries: string[] = [];

for (const entry of entries) {
	const constantName = `m${entry.idx.toString().padStart(4, "0")}`;
	const sqlPath = path.join(migrationsDir, `${entry.tag}.sql`);
	const sql = await readFile(sqlPath, "utf8");
	migrationConstants.push(`const ${constantName} = ${JSON.stringify(sql)};`);
	migrationEntries.push(`\t\t${constantName},`);
}

const contents = `// Generated by packages/scripts/build-do-migrations.ts. Do not edit by hand.
import journal from "./meta/_journal.json";

${migrationConstants.join("\n\n")}

const migrationConfig = {
\tjournal,
\tmigrations: {
${migrationEntries.join("\n")}
\t},
};

export default migrationConfig;
`;

await mkdir(migrationsDir, { recursive: true });
await writeFile(outputPath, contents);
console.log(`Wrote ${outputPath} from ${entries.length} generated Drizzle migration(s).`);
