#!/usr/bin/env bun
import { stdin as input } from "node:process";
import readline from "node:readline";
import { AbortPromptError, CancelPromptError, ExitPromptError } from "@inquirer/core";
import { confirm, input as inputPrompt, password, select } from "@inquirer/prompts";
import pc from "picocolors";
import {
	buildLocalSetupBanner,
	CF_WRANGLER_LOGIN_EXPLAINER,
	formatBanner,
	isUnset,
} from "./utils/env-setup-manifest";
import { getWorkerCatalog, getWorkerNameEnvKeys } from "./utils/prod-env-manifest";
import { isWranglerLoggedIn, runWranglerLogin } from "./utils/wrangler-setup-auth";

/**
 * Interactive first-run: create repo-root `.env.local` with validation.
 * When `.env.local` already exists: show current values and optional per-section updates.
 *
 * - Non-interactive: `bun ... --yes` or stdin not a TTY — if the file exists and no `--force`, exits without changes.
 * - `--force`: full replace (confirm in TTY unless `--yes`).
 *
 * SESSION_SECRET: required at runtime for signed cookies (`apps/web/app/sessions.server.ts`). If missing on write, we generate one.
 *
 * Non-interactive worker names (for CI / agents): optional env
 * **`SETUP_WORKER_PREFIX`** (`isValidWorkerPrefix`) → same `{prefix}-*-dev` names as interactive mode.
 */
const root = Bun.fileURLToPath(new URL("../../..", import.meta.url)).replace(/\/+$/, "");
const dest = `${root}/.env.local`;

function parseLocalCfToken(raw: string | undefined): string | null {
	if (raw === undefined || isUnset(raw)) {
		return null;
	}
	return isPlausibleApiToken(raw) ? raw.trim() : null;
}

function parseLocalCfAccount(raw: string | undefined): string | null {
	if (raw === undefined || isUnset(raw)) {
		return null;
	}
	const t = raw.trim();
	return isAccountId(t) ? t : null;
}

/** Menus only: `q` aborts the prompt (same as Esc/cancel). Not used for text/password fields so you can still type `q`. */
async function withQuit<T>(run: (ctx: { signal?: AbortSignal }) => Promise<T>): Promise<T> {
	if (!input.isTTY) {
		return run({});
	}
	const ac = new AbortController();
	readline.emitKeypressEvents(input);
	const onKeypress = (_: unknown, key: { name?: string }) => {
		if (key?.name === "q") {
			ac.abort();
		}
	};
	input.prependListener("keypress", onKeypress);
	try {
		return await run({ signal: ac.signal });
	} finally {
		input.removeListener("keypress", onKeypress);
	}
}

function parseArgs(argv: string[]) {
	const args = argv.slice(2);
	return {
		yes: args.includes("--yes") || args.includes("-y"),
		force: args.includes("--force"),
	};
}

function randomSessionSecret(): string {
	const bytes = new Uint8Array(32);
	crypto.getRandomValues(bytes);
	let s = "";
	for (const b of bytes) {
		s += String.fromCharCode(b);
	}
	return btoa(s).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function isAccountId(value: string): boolean {
	return /^[a-f0-9]{32}$/i.test(value.trim());
}

function isPlausibleApiToken(value: string): boolean {
	const v = value.trim();
	return v.length >= 30 && !/\s/.test(v);
}

/** Local `*_WORKER_NAME` values keyed like `WEB_WORKER_NAME` (full catalog from templates). */
type LocalWorkerScriptNames = Record<string, string>;

function isValidWorkerPrefix(s: string): boolean {
	const t = s.trim().toLowerCase();
	if (t.length < 1 || t.length > 50) {
		return false;
	}
	return /^[a-z0-9]+([_-][a-z0-9]+)*$/.test(t);
}

function deriveLocalWorkerNames(prefix: string): LocalWorkerScriptNames {
	const p = prefix.trim().toLowerCase();
	const out: LocalWorkerScriptNames = {};
	for (const entry of getWorkerCatalog(root)) {
		if (entry.packageRelDir === "apps/web") {
			out[entry.envKey] = `${p}-web-app-dev`;
		} else if (entry.packageRelDir.startsWith("durable-objects/")) {
			const folder = entry.packageRelDir.replace(/^durable-objects\//, "");
			out[entry.envKey] = `${p}-${folder}-dev`;
		} else if (entry.packageRelDir.startsWith("apps/")) {
			const folder = entry.packageRelDir.replace(/^apps\//, "");
			out[entry.envKey] = `${p}-${folder}-dev`;
		}
	}
	return out;
}

function inferPrefixFromWebWorkerName(web: string): string | undefined {
	const m = /^(.+)-web-app-dev$/i.exec(web.trim());
	return m?.[1]?.toLowerCase();
}

type Answers = {
	sessionSecret: string;
	/** Omitted from `.env.local` when `null` (use `wrangler login` / CI). */
	apiToken: string | null;
	accountId: string | null;
	localWorkerNames: LocalWorkerScriptNames | null;
};

function buildEnv(a: Answers): string {
	let out = `# Generated by bun run setup — edit freely. See repository README for env documentation.

SESSION_SECRET=${escapeEnvValue(a.sessionSecret)}
`;

	if (a.apiToken !== null) {
		out += `CLOUDFLARE_API_TOKEN=${escapeEnvValue(a.apiToken)}\n`;
	}
	if (a.accountId !== null) {
		out += `CLOUDFLARE_ACCOUNT_ID=${escapeEnvValue(a.accountId)}\n`;
	}

	if (a.localWorkerNames) {
		out += `

# Local Wrangler worker script names (optional; omit to use generate-wrangler defaults)
`;
		for (const k of getWorkerNameEnvKeys(root)) {
			const v = a.localWorkerNames[k];
			if (v) {
				out += `${k}=${escapeEnvValue(v)}\n`;
			}
		}
	}

	return out;
}

function escapeEnvValue(value: string): string {
	if (/[\r\n"#]/.test(value)) {
		return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
	}
	return value;
}

type ParsedFromExample = {
	sessionSecret?: string;
	apiToken?: string;
	accountId?: string;
	/** Parsed `*_WORKER_NAME` lines present in the file. */
	workerNames?: Partial<LocalWorkerScriptNames>;
};

function unquoteEnvValue(raw: string): string {
	let val = raw;
	if (val.startsWith('"') && val.endsWith('"')) {
		val = val.slice(1, -1).replaceAll('\\"', '"').replaceAll("\\\\", "\\");
	}
	return val;
}

function parseEnvContent(text: string): ParsedFromExample {
	const out: ParsedFromExample = {};
	const workerKeySet = new Set(getWorkerNameEnvKeys(root));
	for (const line of text.split("\n")) {
		const m =
			/^(SESSION_SECRET|CLOUDFLARE_API_TOKEN|CLOUDFLARE_ACCOUNT_ID|[A-Z][A-Z0-9_]*)=(.*)$/.exec(
				line.trim(),
			);
		if (!m) {
			continue;
		}
		const key = m[1];
		const val = unquoteEnvValue(m[2]);
		if (key === "SESSION_SECRET") {
			out.sessionSecret = val;
			continue;
		}
		if (key === "CLOUDFLARE_API_TOKEN") {
			out.apiToken = val;
			continue;
		}
		if (key === "CLOUDFLARE_ACCOUNT_ID") {
			out.accountId = val;
			continue;
		}
		if (workerKeySet.has(key)) {
			if (!out.workerNames) {
				out.workerNames = {};
			}
			out.workerNames[key] = val;
		}
	}
	return out;
}

async function readParsedFromFile(path: string): Promise<ParsedFromExample> {
	if (!(await Bun.file(path).exists())) {
		return {};
	}
	return parseEnvContent(await Bun.file(path).text());
}

function parsedWorkersToLocal(p: ParsedFromExample): LocalWorkerScriptNames | null {
	if (!p.workerNames) {
		return null;
	}
	const out: LocalWorkerScriptNames = {};
	for (const k of getWorkerNameEnvKeys(root)) {
		const v = p.workerNames[k]?.trim();
		if (!v) {
			return null;
		}
		out[k] = v;
	}
	return out;
}

function answersFromParsed(p: ParsedFromExample): Answers {
	return {
		sessionSecret: p.sessionSecret ?? "",
		apiToken: parseLocalCfToken(p.apiToken),
		accountId: parseLocalCfAccount(p.accountId),
		localWorkerNames: parsedWorkersToLocal(p),
	};
}

function mergeParsed(base: ParsedFromExample, overlay: ParsedFromExample): ParsedFromExample {
	return {
		...base,
		...overlay,
		workerNames:
			base.workerNames || overlay.workerNames
				? { ...base.workerNames, ...overlay.workerNames }
				: undefined,
	};
}

function maskSecret(s: string, visibleEnd = 4): string {
	const t = s.trim();
	if (t.length === 0) {
		return "(empty)";
	}
	if (t.length <= visibleEnd + 4) {
		return "•".repeat(Math.min(12, t.length));
	}
	return `${t.slice(0, 4)}…${t.slice(-visibleEnd)} (${t.length} chars)`;
}

function printSummary(answers: Answers, title = "Current .env.local") {
	console.log();
	console.log(pc.bold(`  ${title}`));
	console.log();

	console.log(pc.bold("  Required"));
	const sess = answers.sessionSecret.trim()
		? maskSecret(answers.sessionSecret)
		: pc.red("missing — required for cookie sessions (web worker)");
	console.log(`    ${pc.dim("SESSION_SECRET")}         ${sess}`);

	console.log();
	console.log(pc.bold("  Optional (OK if omitted)"));
	const cfLine =
		answers.apiToken === null && answers.accountId === null
			? pc.dim("not in file — fine if `bunx wrangler login`")
			: [
					answers.apiToken === null ? "token omitted" : "token set",
					answers.accountId === null ? "account omitted" : "account set",
				].join(", ");
	console.log(`    ${pc.dim("CLOUDFLARE_*")}     ${cfLine}`);

	if (answers.localWorkerNames) {
		const w = answers.localWorkerNames;
		const web = w.WEB_WORKER_NAME ?? Object.values(w)[0] ?? "";
		const pre = inferPrefixFromWebWorkerName(web) ?? "?";
		const preview = getWorkerNameEnvKeys(root)
			.map((k) => w[k])
			.filter(Boolean)
			.slice(0, 4)
			.join(", ");
		console.log(
			`    ${pc.dim("Worker names")}     prefix ${pc.cyan(pre)} → ${preview}${getWorkerNameEnvKeys(root).length > 4 ? ", …" : ""}`,
		);
	} else {
		console.log(
			`    ${pc.dim("Worker names")}     ${pc.dim("not in file — template defaults (cf-*-dev)")}`,
		);
	}
	console.log();
}

async function promptSessionSecretBlock(): Promise<string> {
	const secretMode = await withQuit((ctx) =>
		select<"generate" | "manual">(
			{
				message: "How do you want to set SESSION_SECRET?",
				choices: [
					{ name: "Generate a random secret (recommended)", value: "generate" },
					{ name: "I'll enter my own", value: "manual" },
				],
				default: "generate",
			},
			ctx,
		),
	);

	if (secretMode === "manual") {
		return await inputPrompt({
			message: "SESSION_SECRET (min 16 characters)",
			validate: (v) => {
				if (v.trim().length >= 16) {
					return true;
				}
				return "Use at least 16 characters, or pick Generate above.";
			},
		});
	}
	const s = randomSessionSecret();
	console.log(pc.dim(`  Generated SESSION_SECRET (${s.length} chars).\n`));
	return s;
}

async function promptCloudflareBlock(answers: Answers): Promise<void> {
	console.log(pc.dim(`\n  Cloudflare — optional in this file. ${CF_WRANGLER_LOGIN_EXPLAINER}\n`));
	if (isWranglerLoggedIn()) {
		console.log(pc.dim("  `wrangler whoami` OK — CLI authenticated.\n"));
	} else {
		const runLogin = await withQuit((ctx) =>
			confirm(
				{
					message: "Run `bunx wrangler login` now?",
					default: true,
				},
				ctx,
			),
		);
		if (runLogin) {
			await runWranglerLogin();
		}
	}
	console.log(pc.dim("  Enter to keep current value for each field.\n"));

	const t = await password({
		message: "CLOUDFLARE_API_TOKEN",
		mask: "*",
		validate: (v) => {
			if (isUnset(v)) {
				return true;
			}
			if (isPlausibleApiToken(v)) {
				return true;
			}
			return "30+ chars, no spaces — or Enter to keep current.";
		},
	});
	if (t !== "") {
		if (isUnset(t)) {
			answers.apiToken = null;
		} else {
			answers.apiToken = t.trim();
		}
	}

	const id = await inputPrompt({
		message: "CLOUDFLARE_ACCOUNT_ID (32 hex, or empty to omit from file)",
		default: answers.accountId ?? "",
		validate: (v) => {
			if (v.trim() === "") {
				return true;
			}
			if (isAccountId(v)) {
				return true;
			}
			return "Exactly 32 hex characters — or empty to omit.";
		},
	});
	const idTrim = id.trim();
	answers.accountId = idTrim === "" ? null : idTrim;
}

async function promptWorkerBlock(
	exampleDefaults: ParsedFromExample,
	current: Answers,
): Promise<void> {
	const mergedWorkers: ParsedFromExample = { workerNames: { ...exampleDefaults.workerNames } };
	if (current.localWorkerNames) {
		if (!mergedWorkers.workerNames) {
			mergedWorkers.workerNames = {};
		}
		for (const k of getWorkerNameEnvKeys(root)) {
			mergedWorkers.workerNames[k] = current.localWorkerNames[k] ?? mergedWorkers.workerNames[k];
		}
	}
	const merged = mergeParsed(exampleDefaults, mergedWorkers);

	const sub = await withQuit((ctx) =>
		select<"template" | "prefix" | "cancel">(
			{
				message: "Local worker script names",
				choices: [
					{
						name: "Use template defaults (remove WEB_* / *_DO_* overrides from file)",
						value: "template",
					},
					{
						name: "Set a custom prefix (e.g. acme → acme-web-app-dev, …)",
						value: "prefix",
					},
					{ name: "Cancel", value: "cancel" },
				],
				default: "cancel",
			},
			ctx,
		),
	);

	if (sub === "cancel") {
		return;
	}
	if (sub === "template") {
		current.localWorkerNames = null;
		console.log(pc.dim("  Using built-in cf-*-dev names from generate-wrangler.\n"));
		return;
	}

	const webFromMerged =
		merged.workerNames?.WEB_WORKER_NAME ?? current.localWorkerNames?.WEB_WORKER_NAME ?? "";
	const prefixDefault = inferPrefixFromWebWorkerName(webFromMerged) ?? "cf";
	const prefix = await inputPrompt({
		message: "Worker name prefix",
		default: prefixDefault,
		validate: (v) =>
			isValidWorkerPrefix(v) || "1–50 chars: lowercase letters, numbers, hyphens, underscores.",
	});
	current.localWorkerNames = deriveLocalWorkerNames(prefix);
	const names = getWorkerNameEnvKeys(root)
		.map((k) => current.localWorkerNames?.[k])
		.filter(Boolean);
	console.log(pc.dim(`  ${names.join(", ")}\n`));
}

async function promptCloudflareInteractiveLocal(): Promise<{
	apiToken: string | null;
	accountId: string | null;
}> {
	let apiToken: string | null = null;
	let accountId: string | null = null;

	console.log(
		pc.dim(`\n  Cloudflare — optional in this file.\n  ${CF_WRANGLER_LOGIN_EXPLAINER}\n`),
	);

	if (isWranglerLoggedIn()) {
		console.log(pc.green("  Wrangler CLI is already authenticated (`wrangler whoami` OK).\n"));
	} else {
		console.log(
			pc.yellow("  Wrangler is not authenticated yet (`wrangler whoami` did not succeed).\n"),
		);
		const runLogin = await withQuit((ctx) =>
			confirm(
				{
					message: "Run `bunx wrangler login` now? (Opens a browser)",
					default: true,
				},
				ctx,
			),
		);
		if (runLogin) {
			console.log(pc.dim("  Running wrangler login…\n"));
			const ok = await runWranglerLogin();
			if (ok && isWranglerLoggedIn()) {
				console.log(pc.green("  Login successful.\n"));
			} else {
				console.log(
					pc.yellow("  Login may be incomplete — run `bunx wrangler login` yourself when ready.\n"),
				);
			}
		}
	}

	const addTokens = await withQuit((ctx) =>
		confirm(
			{
				message:
					"Optionally store CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID in .env.local? (For CI/headless, or if you prefer API tokens over OAuth.)",
				default: false,
			},
			ctx,
		),
	);

	if (!addTokens) {
		return { apiToken, accountId };
	}

	console.log(
		pc.dim(
			"\n  Dashboard: Workers → Overview → Account ID · User Profile → API Tokens → Create.\n",
		),
	);
	console.log(
		pc.dim("  Press Enter to skip a field — values are omitted from the file unless set.\n"),
	);

	const t = await password({
		message: "CLOUDFLARE_API_TOKEN (Enter to skip)",
		mask: "*",
		validate: (v) => {
			if (isUnset(v)) {
				return true;
			}
			if (isPlausibleApiToken(v)) {
				return true;
			}
			return "Expected 30+ characters, no spaces — or Enter to skip.";
		},
	});
	if (isUnset(t)) {
		apiToken = null;
	} else {
		apiToken = t.trim();
	}

	const id = await inputPrompt({
		message: "CLOUDFLARE_ACCOUNT_ID (32 hex chars, or leave empty to omit)",
		validate: (v) => {
			if (v.trim() === "") {
				return true;
			}
			if (isAccountId(v)) {
				return true;
			}
			return "Account ID must be exactly 32 hex characters (a–f, 0–9).";
		},
	});
	accountId = id.trim() === "" ? null : id.trim();

	return { apiToken, accountId };
}

async function interactive(seed?: ParsedFromExample): Promise<Answers> {
	const defaults = mergeParsed({}, seed ?? {});

	console.log();
	console.log(pc.bold("  Env setup"));
	console.log(pc.dim("  Create or replace .env.local for local dev."));
	console.log(pc.dim(formatBanner(buildLocalSetupBanner(root))));
	console.log(pc.dim("  At yes/no and list menus: press q to exit (same as Esc).\n"));

	const sessionSecret = await promptSessionSecretBlock();

	console.log(
		pc.dim(
			"\n  Local Wrangler worker script names (*-dev). Production names: .env.production when you deploy.\n",
		),
	);

	let localWorkerNames: LocalWorkerScriptNames | null = null;
	const customizeWorkers = await withQuit((ctx) =>
		confirm(
			{
				message:
					'Use a custom prefix for local worker names? (e.g. "acme" → acme-web-app-dev, …). Otherwise template defaults (cf-*).',
				default: false,
			},
			ctx,
		),
	);

	if (customizeWorkers) {
		const prefixDefault =
			inferPrefixFromWebWorkerName(defaults.workerNames?.WEB_WORKER_NAME ?? "") ?? "cf";
		const prefix = await inputPrompt({
			message: "Worker name prefix",
			default: prefixDefault,
			validate: (v) =>
				isValidWorkerPrefix(v) ||
				"Use 1–50 chars: lowercase letters, numbers, hyphens, underscores (e.g. my-app).",
		});
		localWorkerNames = deriveLocalWorkerNames(prefix);
		const preview = getWorkerNameEnvKeys(root)
			.map((k) => localWorkerNames?.[k])
			.filter(Boolean)
			.join(", ");
		console.log(pc.dim(`  ${preview}\n`));
	}

	const { apiToken, accountId } = await promptCloudflareInteractiveLocal();

	return {
		sessionSecret,
		apiToken,
		accountId,
		localWorkerNames,
	};
}

async function defaultsNonInteractive(): Promise<Answers> {
	const fromFile: ParsedFromExample = {};

	let localWorkerNames = parsedWorkersToLocal(fromFile);
	const prefixFromEnv = process.env.SETUP_WORKER_PREFIX?.trim();
	if (prefixFromEnv) {
		if (isValidWorkerPrefix(prefixFromEnv)) {
			localWorkerNames = deriveLocalWorkerNames(prefixFromEnv);
		} else {
			console.warn(
				pc.yellow(
					`SETUP_WORKER_PREFIX is invalid — ignoring. Use lowercase letters, numbers, hyphens, underscores (1–50 chars). Got: ${prefixFromEnv.slice(0, 40)}`,
				),
			);
		}
	}

	return {
		sessionSecret: randomSessionSecret(),
		apiToken: parseLocalCfToken(fromFile.apiToken),
		accountId: parseLocalCfAccount(fromFile.accountId),
		localWorkerNames,
	};
}

function afterWriteHints(answers: Answers) {
	if (answers.localWorkerNames) {
		console.log(
			pc.dim(
				"Run bun run typegen or bun run dev so generated wrangler config picks up worker names.",
			),
		);
	}
	if (answers.apiToken === null && answers.accountId === null) {
		console.log(pc.dim(`Optional Cloudflare: ${CF_WRANGLER_LOGIN_EXPLAINER}`));
	} else if (answers.apiToken === null || answers.accountId === null) {
		console.log(
			pc.dim(
				"Cloudflare: you only set one of token/account — add both for API-token flows, or omit both and use `bunx wrangler login`.",
			),
		);
	}
}

async function writeDest(answers: Answers) {
	let generatedSession = false;
	if (!answers.sessionSecret.trim()) {
		answers.sessionSecret = randomSessionSecret();
		generatedSession = true;
	}
	await Bun.write(dest, buildEnv(answers));
	console.log();
	console.log(pc.green(`Wrote ${dest}`));
	if (generatedSession) {
		console.log(
			pc.dim(
				"SESSION_SECRET was empty — generated one (required for signed cookies / sessions in the web worker).",
			),
		);
	}
	afterWriteHints(answers);
}

async function interactiveUpdateExisting(): Promise<void> {
	const raw = await readParsedFromFile(dest);
	let answers = answersFromParsed(raw);

	console.log(pc.dim("  At list/yes-no menus: q = quit · Esc = cancel · Ctrl+C = exit.\n"));
	console.log(pc.dim(formatBanner(buildLocalSetupBanner(root))));
	console.log();

	for (;;) {
		printSummary(answers);

		const action = await withQuit((ctx) =>
			select<"done" | "session" | "cloudflare" | "workers" | "full">(
				{
					message: "What do you want to change?",
					choices: [
						{ name: "Nothing — exit", value: "done" },
						{ name: "SESSION_SECRET", value: "session" },
						{ name: "Cloudflare API token & account ID", value: "cloudflare" },
						{ name: "Local worker names (prefix or template defaults)", value: "workers" },
						{ name: "Re-run full setup wizard (replace all fields)", value: "full" },
					],
					default: "done",
				},
				ctx,
			),
		);

		if (action === "done") {
			console.log(pc.dim("No changes this run. Edit the file by hand anytime."));
			return;
		}

		if (action === "full") {
			const go = await withQuit((ctx) =>
				confirm(
					{
						message:
							"Run the full wizard? You will re-enter every field (seeded from your current file where possible).",
						default: false,
					},
					ctx,
				),
			);
			if (!go) {
				continue;
			}
			const seed = mergeParsed({}, raw);
			answers = await interactive(seed);
			await writeDest(answers);
			return;
		}

		if (action === "session") {
			answers.sessionSecret = await promptSessionSecretBlock();
			await writeDest(answers);
			continue;
		}

		if (action === "cloudflare") {
			await promptCloudflareBlock(answers);
			await writeDest(answers);
			continue;
		}

		if (action === "workers") {
			await promptWorkerBlock({}, answers);
			await writeDest(answers);
		}
	}
}

async function main() {
	const { yes, force } = parseArgs(process.argv);
	const nonInteractive = yes || !input.isTTY;

	const destExists = await Bun.file(dest).exists();

	if (destExists && !force && !nonInteractive) {
		await interactiveUpdateExisting();
		return;
	}

	if (destExists && !force && nonInteractive) {
		console.log(pc.yellow(".env.local already exists — skipped (non-interactive)."));
		console.log(pc.dim("  bun run setup          # review / update interactively"));
		console.log(pc.dim("  bun run setup --force  # replace the whole file"));
		process.exit(0);
	}

	if (destExists && force && !nonInteractive) {
		const ok = await withQuit((ctx) =>
			confirm(
				{
					message: pc.yellow("Overwrite existing .env.local with a new full setup?"),
					default: false,
				},
				ctx,
			),
		);
		if (!ok) {
			console.log(pc.dim("Cancelled."));
			process.exit(0);
		}
	}

	let answers: Answers;
	if (nonInteractive) {
		answers = await defaultsNonInteractive();
	} else {
		const seed = destExists && force ? mergeParsed({}, await readParsedFromFile(dest)) : undefined;
		answers = await interactive(seed);
	}

	await writeDest(answers);
}

try {
	await main();
} catch (e) {
	if (
		e instanceof ExitPromptError ||
		e instanceof CancelPromptError ||
		e instanceof AbortPromptError
	) {
		console.log(pc.dim("\nCancelled."));
		process.exit(0);
	}
	throw e;
}
