#!/usr/bin/env bun
import { stdin as input } from "node:process";
import readline from "node:readline";
import { AbortPromptError, CancelPromptError, ExitPromptError } from "@inquirer/core";
import { confirm, input as inputPrompt, password, select } from "@inquirer/prompts";
import pc from "picocolors";

/**
 * Interactive first-run: create repo-root `.env.local` with validation.
 * When `.env.local` already exists: show current values and optional per-section updates.
 *
 * - Non-interactive: `bun ... --yes` or stdin not a TTY — if the file exists and no `--force`, exits without changes.
 * - `--force`: full replace (confirm in TTY unless `--yes`).
 *
 * SESSION_SECRET: required at runtime for signed cookies (`apps/web/app/sessions.server.ts`). If missing on write, we generate one.
 *
 * Non-interactive worker + demo strings (for CI / agents): optional env
 * **`SETUP_WORKER_PREFIX`** (`isValidWorkerPrefix`) → same `{prefix}-*-dev` names as interactive mode.
 * **`SETUP_VALUE_FROM_CLOUDFLARE`** → demo UI string (overrides .env.example).
 */
const root = Bun.fileURLToPath(new URL("../../..", import.meta.url)).replace(/\/+$/, "");
const dest = `${root}/.env.local`;
const src = `${root}/.env.example`;

const PLACEHOLDER_TOKEN = "replace_me_after_cp_to_env_local";

/** Menus only: `q` aborts the prompt (same as Esc/cancel). Not used for text/password fields so you can still type `q`. */
async function withQuit<T>(run: (ctx: { signal?: AbortSignal }) => Promise<T>): Promise<T> {
	if (!input.isTTY) {
		return run({});
	}
	const ac = new AbortController();
	readline.emitKeypressEvents(input);
	const onKeypress = (_: unknown, key: { name?: string }) => {
		if (key?.name === "q") {
			ac.abort();
		}
	};
	input.prependListener("keypress", onKeypress);
	try {
		return await run({ signal: ac.signal });
	} finally {
		input.removeListener("keypress", onKeypress);
	}
}

function parseArgs(argv: string[]) {
	const args = argv.slice(2);
	return {
		yes: args.includes("--yes") || args.includes("-y"),
		force: args.includes("--force"),
	};
}

function randomSessionSecret(): string {
	const bytes = new Uint8Array(32);
	crypto.getRandomValues(bytes);
	let s = "";
	for (const b of bytes) {
		s += String.fromCharCode(b);
	}
	return btoa(s).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function isAccountId(value: string): boolean {
	return /^[a-f0-9]{32}$/i.test(value.trim());
}

function isPlausibleApiToken(value: string): boolean {
	const v = value.trim();
	if (v.length < 30) {
		return false;
	}
	if (/\s/.test(v)) {
		return false;
	}
	if (/^replace|^changeme|^your_|^xxx$/i.test(v)) {
		return false;
	}
	if (v === PLACEHOLDER_TOKEN) {
		return false;
	}
	return !looksIncomplete(v);
}

function looksIncomplete(value: string): boolean {
	const v = value.trim().toLowerCase();
	if (v === "" || v === PLACEHOLDER_TOKEN) {
		return true;
	}
	return /^replace_me/i.test(v);
}

type LocalWorkerNames = {
	web: string;
	exampleDo: string;
	coordinatorDo: string;
	processorDo: string;
};

function isValidWorkerPrefix(s: string): boolean {
	const t = s.trim().toLowerCase();
	if (t.length < 1 || t.length > 50) {
		return false;
	}
	return /^[a-z0-9]+([_-][a-z0-9]+)*$/.test(t);
}

function deriveLocalWorkerNames(prefix: string): LocalWorkerNames {
	const p = prefix.trim().toLowerCase();
	return {
		web: `${p}-web-app-dev`,
		exampleDo: `${p}-example-do-dev`,
		coordinatorDo: `${p}-coordinator-do-dev`,
		processorDo: `${p}-processor-do-dev`,
	};
}

function inferPrefixFromWebWorkerName(web: string): string | undefined {
	const m = /^(.+)-web-app-dev$/i.exec(web.trim());
	return m?.[1]?.toLowerCase();
}

type Answers = {
	sessionSecret: string;
	valueFromCloudflare: string;
	apiToken: string;
	accountId: string;
	localWorkerNames: LocalWorkerNames | null;
};

function buildEnv(a: Answers): string {
	let out = `# Generated by bun run setup — edit freely. See README and .env.example.

SESSION_SECRET=${escapeEnvValue(a.sessionSecret)}
VALUE_FROM_CLOUDFLARE=${escapeEnvValue(a.valueFromCloudflare)}
CLOUDFLARE_API_TOKEN=${escapeEnvValue(a.apiToken)}
CLOUDFLARE_ACCOUNT_ID=${escapeEnvValue(a.accountId)}
`;

	if (a.localWorkerNames) {
		const w = a.localWorkerNames;
		out += `

# Local Wrangler worker script names (optional; omit to use generate-wrangler defaults)
WEB_WORKER_NAME=${escapeEnvValue(w.web)}
EXAMPLE_DO_WORKER_NAME=${escapeEnvValue(w.exampleDo)}
COORDINATOR_DO_WORKER_NAME=${escapeEnvValue(w.coordinatorDo)}
PROCESSOR_DO_WORKER_NAME=${escapeEnvValue(w.processorDo)}
`;
	}

	return out;
}

function escapeEnvValue(value: string): string {
	if (/[\r\n"#]/.test(value)) {
		return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
	}
	return value;
}

type ParsedFromExample = {
	sessionSecret?: string;
	valueFromCloudflare?: string;
	apiToken?: string;
	accountId?: string;
	webWorkerName?: string;
	exampleDoWorkerName?: string;
	coordinatorDoWorkerName?: string;
	processorDoWorkerName?: string;
};

const ENV_KEY_TO_PARSED: Record<string, keyof ParsedFromExample> = {
	SESSION_SECRET: "sessionSecret",
	VALUE_FROM_CLOUDFLARE: "valueFromCloudflare",
	CLOUDFLARE_API_TOKEN: "apiToken",
	CLOUDFLARE_ACCOUNT_ID: "accountId",
	WEB_WORKER_NAME: "webWorkerName",
	EXAMPLE_DO_WORKER_NAME: "exampleDoWorkerName",
	COORDINATOR_DO_WORKER_NAME: "coordinatorDoWorkerName",
	PROCESSOR_DO_WORKER_NAME: "processorDoWorkerName",
};

function parseEnvContent(text: string): ParsedFromExample {
	const out: ParsedFromExample = {};
	for (const line of text.split("\n")) {
		const m =
			/^(SESSION_SECRET|VALUE_FROM_CLOUDFLARE|CLOUDFLARE_API_TOKEN|CLOUDFLARE_ACCOUNT_ID|WEB_WORKER_NAME|EXAMPLE_DO_WORKER_NAME|COORDINATOR_DO_WORKER_NAME|PROCESSOR_DO_WORKER_NAME)=(.*)$/.exec(
				line.trim(),
			);
		if (!m) {
			continue;
		}
		const prop = ENV_KEY_TO_PARSED[m[1]];
		if (!prop) {
			continue;
		}
		let val = m[2];
		if (val.startsWith('"') && val.endsWith('"')) {
			val = val.slice(1, -1).replaceAll('\\"', '"').replaceAll("\\\\", "\\");
		}
		out[prop] = val;
	}
	return out;
}

async function readParsedFromFile(path: string): Promise<ParsedFromExample> {
	if (!(await Bun.file(path).exists())) {
		return {};
	}
	return parseEnvContent(await Bun.file(path).text());
}

async function readDefaultsFromExample(): Promise<ParsedFromExample> {
	return readParsedFromFile(src);
}

function parsedWorkersToLocal(p: ParsedFromExample): LocalWorkerNames | null {
	const { webWorkerName, exampleDoWorkerName, coordinatorDoWorkerName, processorDoWorkerName } = p;
	if (webWorkerName && exampleDoWorkerName && coordinatorDoWorkerName && processorDoWorkerName) {
		return {
			web: webWorkerName,
			exampleDo: exampleDoWorkerName,
			coordinatorDo: coordinatorDoWorkerName,
			processorDo: processorDoWorkerName,
		};
	}
	return null;
}

function answersFromParsed(p: ParsedFromExample): Answers {
	return {
		sessionSecret: p.sessionSecret ?? "",
		valueFromCloudflare: p.valueFromCloudflare ?? "Hello from local dev",
		apiToken: p.apiToken ?? PLACEHOLDER_TOKEN,
		accountId: p.accountId ?? PLACEHOLDER_TOKEN,
		localWorkerNames: parsedWorkersToLocal(p),
	};
}

function mergeParsed(base: ParsedFromExample, overlay: ParsedFromExample): ParsedFromExample {
	return { ...base, ...overlay };
}

function maskSecret(s: string, visibleEnd = 4): string {
	const t = s.trim();
	if (t.length === 0) {
		return "(empty)";
	}
	if (t.length <= visibleEnd + 4) {
		return "•".repeat(Math.min(12, t.length));
	}
	return `${t.slice(0, 4)}…${t.slice(-visibleEnd)} (${t.length} chars)`;
}

function formatTokenLine(t: string): string {
	if (looksIncomplete(t)) {
		return pc.yellow("not set (placeholder)");
	}
	return maskSecret(t);
}

function printSummary(answers: Answers, title = "Current .env.local") {
	console.log();
	console.log(pc.bold(`  ${title}`));
	console.log();

	const sess = answers.sessionSecret.trim()
		? maskSecret(answers.sessionSecret)
		: `${pc.yellow("not set")}${pc.dim(" — needed for cookie sessions (web worker)")}`;
	console.log(`  ${pc.dim("SESSION_SECRET")}         ${sess}`);

	console.log(`  ${pc.dim("VALUE_FROM_CLOUDFLARE")}  ${answers.valueFromCloudflare}`);

	console.log(`  ${pc.dim("CLOUDFLARE_API_TOKEN")}  ${formatTokenLine(answers.apiToken)}`);
	const aid = answers.accountId.trim();
	console.log(
		`  ${pc.dim("CLOUDFLARE_ACCOUNT_ID")}  ${
			looksIncomplete(aid)
				? pc.yellow("not set (placeholder)")
				: `${aid.slice(0, 8)}… (${aid.length} hex)`
		}`,
	);

	if (answers.localWorkerNames) {
		const w = answers.localWorkerNames;
		const pre = inferPrefixFromWebWorkerName(w.web) ?? "?";
		console.log(
			`  ${pc.dim("Worker names")}         prefix ${pc.cyan(pre)} → ${w.web}, ${w.exampleDo}, …`,
		);
	} else {
		console.log(
			`  ${pc.dim("Worker names")}         ${pc.dim("template defaults (cf-*-dev) — no overrides in file")}`,
		);
	}
	console.log();
}

async function promptSessionSecretBlock(): Promise<string> {
	const secretMode = await withQuit((ctx) =>
		select<"generate" | "manual">(
			{
				message: "How do you want to set SESSION_SECRET?",
				choices: [
					{ name: "Generate a random secret (recommended)", value: "generate" },
					{ name: "I'll enter my own", value: "manual" },
				],
				default: "generate",
			},
			ctx,
		),
	);

	if (secretMode === "manual") {
		return await inputPrompt({
			message: "SESSION_SECRET (min 16 characters)",
			validate: (v) => {
				if (v.trim().length >= 16) {
					return true;
				}
				return "Use at least 16 characters, or pick Generate above.";
			},
		});
	}
	const s = randomSessionSecret();
	console.log(pc.dim(`  Generated SESSION_SECRET (${s.length} chars).\n`));
	return s;
}

async function promptCloudflareBlock(answers: Answers): Promise<void> {
	console.log(pc.dim("  Enter to keep current value.\n"));

	const t = await password({
		message: "CLOUDFLARE_API_TOKEN",
		mask: "*",
		validate: (v) => {
			if (v === "") {
				return true;
			}
			if (looksIncomplete(v)) {
				return true;
			}
			if (isPlausibleApiToken(v)) {
				return true;
			}
			return "30+ chars, no spaces — or Enter to keep current.";
		},
	});
	if (t !== "") {
		if (looksIncomplete(t)) {
			answers.apiToken = PLACEHOLDER_TOKEN;
		} else {
			answers.apiToken = t.trim();
		}
	}

	const id = await inputPrompt({
		message: "CLOUDFLARE_ACCOUNT_ID (32 hex, or empty for placeholder)",
		default: looksIncomplete(answers.accountId) ? "" : answers.accountId,
		validate: (v) => {
			if (v.trim() === "") {
				return true;
			}
			if (isAccountId(v)) {
				return true;
			}
			return "Exactly 32 hex characters — or empty for placeholder.";
		},
	});
	answers.accountId = id.trim() === "" ? PLACEHOLDER_TOKEN : id.trim();
}

async function promptWorkerBlock(
	exampleDefaults: ParsedFromExample,
	current: Answers,
): Promise<void> {
	const merged = mergeParsed(exampleDefaults, {
		webWorkerName: current.localWorkerNames?.web,
		exampleDoWorkerName: current.localWorkerNames?.exampleDo,
		coordinatorDoWorkerName: current.localWorkerNames?.coordinatorDo,
		processorDoWorkerName: current.localWorkerNames?.processorDo,
	});

	const sub = await withQuit((ctx) =>
		select<"template" | "prefix" | "cancel">(
			{
				message: "Local worker script names",
				choices: [
					{
						name: "Use template defaults (remove WEB_* / *_DO_* overrides from file)",
						value: "template",
					},
					{
						name: "Set a custom prefix (e.g. acme → acme-web-app-dev, …)",
						value: "prefix",
					},
					{ name: "Cancel", value: "cancel" },
				],
				default: "cancel",
			},
			ctx,
		),
	);

	if (sub === "cancel") {
		return;
	}
	if (sub === "template") {
		current.localWorkerNames = null;
		console.log(pc.dim("  Using built-in cf-*-dev names from generate-wrangler.\n"));
		return;
	}

	const prefixDefault =
		inferPrefixFromWebWorkerName(merged.webWorkerName ?? current.localWorkerNames?.web ?? "") ??
		"cf";
	const prefix = await inputPrompt({
		message: "Worker name prefix",
		default: prefixDefault,
		validate: (v) =>
			isValidWorkerPrefix(v) || "1–50 chars: lowercase letters, numbers, hyphens, underscores.",
	});
	current.localWorkerNames = deriveLocalWorkerNames(prefix);
	console.log(
		pc.dim(
			`  ${current.localWorkerNames.web}, ${current.localWorkerNames.exampleDo}, ${current.localWorkerNames.coordinatorDo}, ${current.localWorkerNames.processorDo}\n`,
		),
	);
}

async function interactive(seed?: ParsedFromExample): Promise<Answers> {
	const example = await readDefaultsFromExample();
	const defaults = mergeParsed(example, seed ?? {});

	console.log();
	console.log(pc.bold("  Env setup"));
	console.log(pc.dim("  Create or replace .env.local for local dev."));
	console.log(pc.dim("  At yes/no and list menus: press q to exit (same as Esc).\n"));

	const sessionSecret = await promptSessionSecretBlock();

	const valueFromCloudflare =
		(await inputPrompt({
			message: "VALUE_FROM_CLOUDFLARE (string shown in the demo UI)",
			default: defaults.valueFromCloudflare ?? "Hello from local dev",
		})) || "Hello from local dev";

	console.log(
		pc.dim(
			"\n  Local Wrangler worker script names (*-dev). Production names: .env.production when you deploy.\n",
		),
	);

	let localWorkerNames: LocalWorkerNames | null = null;
	const customizeWorkers = await withQuit((ctx) =>
		confirm(
			{
				message:
					'Use a custom prefix for local worker names? (e.g. "acme" → acme-web-app-dev, …). Otherwise template defaults (cf-*).',
				default: false,
			},
			ctx,
		),
	);

	if (customizeWorkers) {
		const prefixDefault = inferPrefixFromWebWorkerName(defaults.webWorkerName ?? "") ?? "cf";
		const prefix = await inputPrompt({
			message: "Worker name prefix",
			default: prefixDefault,
			validate: (v) =>
				isValidWorkerPrefix(v) ||
				"Use 1–50 chars: lowercase letters, numbers, hyphens, underscores (e.g. my-app).",
		});
		localWorkerNames = deriveLocalWorkerNames(prefix);
		console.log(
			pc.dim(
				`  Web: ${localWorkerNames.web} · DOs: ${localWorkerNames.exampleDo}, ${localWorkerNames.coordinatorDo}, ${localWorkerNames.processorDo}\n`,
			),
		);
	}

	let apiToken = PLACEHOLDER_TOKEN;
	let accountId = PLACEHOLDER_TOKEN;

	const wantCf = await withQuit((ctx) =>
		confirm(
			{
				message:
					"Set Cloudflare API token and account ID now? (Needed for wrangler deploy; often not required for local dev.)",
				default: false,
			},
			ctx,
		),
	);

	if (wantCf) {
		console.log(
			pc.dim(
				"\n  Dashboard: Workers → Overview → Account ID · User Profile → API Tokens → Create.\n",
			),
		);

		const t = await password({
			message: "CLOUDFLARE_API_TOKEN (Enter to skip)",
			mask: "*",
			validate: (v) => {
				if (v === "" || looksIncomplete(v)) {
					return true;
				}
				if (isPlausibleApiToken(v)) {
					return true;
				}
				return "Expected 30+ characters, no spaces — or press Enter to skip.";
			},
		});
		if (t === "" || looksIncomplete(t)) {
			apiToken = PLACEHOLDER_TOKEN;
		} else {
			apiToken = t.trim();
		}

		const id = await inputPrompt({
			message: "CLOUDFLARE_ACCOUNT_ID (32 hex chars, or leave empty to skip)",
			validate: (v) => {
				if (v.trim() === "") {
					return true;
				}
				if (isAccountId(v)) {
					return true;
				}
				return "Account ID must be exactly 32 hex characters (a–f, 0–9).";
			},
		});
		accountId = id.trim() === "" ? PLACEHOLDER_TOKEN : id.trim();
	}

	return {
		sessionSecret,
		valueFromCloudflare,
		apiToken,
		accountId,
		localWorkerNames,
	};
}

async function defaultsNonInteractive(): Promise<Answers> {
	const fromExample = await readDefaultsFromExample();
	const demoFromEnv = process.env.SETUP_VALUE_FROM_CLOUDFLARE?.trim();
	const valueFromCloudflare =
		demoFromEnv && demoFromEnv.length > 0
			? demoFromEnv
			: (fromExample.valueFromCloudflare ?? "Hello from local dev");

	let localWorkerNames = parsedWorkersToLocal(fromExample);
	const prefixFromEnv = process.env.SETUP_WORKER_PREFIX?.trim();
	if (prefixFromEnv) {
		if (isValidWorkerPrefix(prefixFromEnv)) {
			localWorkerNames = deriveLocalWorkerNames(prefixFromEnv);
		} else {
			console.warn(
				pc.yellow(
					`SETUP_WORKER_PREFIX is invalid — ignoring. Use lowercase letters, numbers, hyphens, underscores (1–50 chars). Got: ${prefixFromEnv.slice(0, 40)}`,
				),
			);
		}
	}

	return {
		sessionSecret: randomSessionSecret(),
		valueFromCloudflare,
		apiToken:
			fromExample.apiToken && !looksIncomplete(fromExample.apiToken)
				? fromExample.apiToken
				: PLACEHOLDER_TOKEN,
		accountId:
			fromExample.accountId && isAccountId(fromExample.accountId)
				? fromExample.accountId
				: PLACEHOLDER_TOKEN,
		localWorkerNames,
	};
}

function afterWriteHints(answers: Answers) {
	if (answers.localWorkerNames) {
		console.log(
			pc.dim(
				"Run bun run typegen or bun run dev so generated wrangler config picks up worker names.",
			),
		);
	}
	if (looksIncomplete(answers.apiToken) || looksIncomplete(answers.accountId)) {
		console.log(
			pc.dim("Deploy: set CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID before wrangler deploy."),
		);
	}
}

async function writeDest(answers: Answers) {
	let generatedSession = false;
	if (!answers.sessionSecret.trim()) {
		answers.sessionSecret = randomSessionSecret();
		generatedSession = true;
	}
	await Bun.write(dest, buildEnv(answers));
	console.log();
	console.log(pc.green(`Wrote ${dest}`));
	if (generatedSession) {
		console.log(
			pc.dim(
				"SESSION_SECRET was empty — generated one (required for signed cookies / sessions in the web worker).",
			),
		);
	}
	afterWriteHints(answers);
}

async function interactiveUpdateExisting(): Promise<void> {
	const raw = await readParsedFromFile(dest);
	const example = await readDefaultsFromExample();
	let answers = answersFromParsed(raw);

	console.log(pc.dim("  At list/yes-no menus: q = quit · Esc = cancel · Ctrl+C = exit.\n"));

	for (;;) {
		printSummary(answers);

		const action = await withQuit((ctx) =>
			select<"done" | "session" | "demo" | "cloudflare" | "workers" | "full">(
				{
					message: "What do you want to change?",
					choices: [
						{ name: "Nothing — exit", value: "done" },
						{ name: "SESSION_SECRET", value: "session" },
						{ name: "VALUE_FROM_CLOUDFLARE (demo UI string)", value: "demo" },
						{ name: "Cloudflare API token & account ID", value: "cloudflare" },
						{ name: "Local worker names (prefix or template defaults)", value: "workers" },
						{ name: "Re-run full setup wizard (replace all fields)", value: "full" },
					],
					default: "done",
				},
				ctx,
			),
		);

		if (action === "done") {
			console.log(pc.dim("No changes this run. Edit the file by hand anytime."));
			return;
		}

		if (action === "full") {
			const go = await withQuit((ctx) =>
				confirm(
					{
						message:
							"Run the full wizard? You will re-enter every field (seeded from your current file where possible).",
						default: false,
					},
					ctx,
				),
			);
			if (!go) {
				continue;
			}
			const seed = mergeParsed(example, raw);
			answers = await interactive(seed);
			await writeDest(answers);
			return;
		}

		if (action === "session") {
			answers.sessionSecret = await promptSessionSecretBlock();
			await writeDest(answers);
			continue;
		}

		if (action === "demo") {
			answers.valueFromCloudflare =
				(await inputPrompt({
					message: "VALUE_FROM_CLOUDFLARE",
					default: answers.valueFromCloudflare || "Hello from local dev",
				})) || "Hello from local dev";
			await writeDest(answers);
			continue;
		}

		if (action === "cloudflare") {
			await promptCloudflareBlock(answers);
			await writeDest(answers);
			continue;
		}

		if (action === "workers") {
			await promptWorkerBlock(example, answers);
			await writeDest(answers);
		}
	}
}

async function main() {
	const { yes, force } = parseArgs(process.argv);
	const nonInteractive = yes || !input.isTTY;

	if (!(await Bun.file(src).exists())) {
		console.error(pc.red("Missing .env.example at repo root."));
		process.exit(1);
	}

	const destExists = await Bun.file(dest).exists();

	if (destExists && !force && !nonInteractive) {
		await interactiveUpdateExisting();
		return;
	}

	if (destExists && !force && nonInteractive) {
		console.log(pc.yellow(".env.local already exists — skipped (non-interactive)."));
		console.log(pc.dim("  bun run setup          # review / update interactively"));
		console.log(pc.dim("  bun run setup --force  # replace the whole file"));
		process.exit(0);
	}

	if (destExists && force && !nonInteractive) {
		const ok = await withQuit((ctx) =>
			confirm(
				{
					message: pc.yellow("Overwrite existing .env.local with a new full setup?"),
					default: false,
				},
				ctx,
			),
		);
		if (!ok) {
			console.log(pc.dim("Cancelled."));
			process.exit(0);
		}
	}

	let answers: Answers;
	if (nonInteractive) {
		answers = await defaultsNonInteractive();
	} else {
		const seed =
			destExists && force
				? mergeParsed(await readDefaultsFromExample(), await readParsedFromFile(dest))
				: undefined;
		answers = await interactive(seed);
	}

	await writeDest(answers);
}

try {
	await main();
} catch (e) {
	if (
		e instanceof ExitPromptError ||
		e instanceof CancelPromptError ||
		e instanceof AbortPromptError
	) {
		console.log(pc.dim("\nCancelled."));
		process.exit(0);
	}
	throw e;
}
